kind: pipeline
name: default

steps:
- name: setup
  image: node:lts-slim
  commands:
  - npm ci

- name: unit
  image: node:lts-slim
  commands:
  - npm run test:unit
  depends_on:
  - setup

- name: e2e
  image: cypress/browsers:chrome67
  commands:
  - npm i @vue/cli-plugin-e2e-cypress@4.0.5 cypress
  - npm run test:e2e -- --headless
  depends_on:
  - setup