kind: pipeline
type: kubernetes
name: default

steps:
- name: setup
  image: node:lts-slim
  commands:
  - npm ci
  - npm run build

- name: unit
  image: node:lts-slim
  commands:
  - npm run test:unit
  depends_on:
    - setup

- name: e2e
  image: node:lts-slim
  commands:
  - npm run test:e2e
  depends_on:
    - setup