version: 2.1

executors:
  # define node executor specs
  node-executor: &node-executor
    docker:
      - image: node:lts-slim
    resource_class: small
    working_directory: *workspace_root

references:
  workspace_root: &workspace_root
  /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

workflows:
  version: 2
  setup:
    jobs:
      - setup
  tests:
    jobs:
      - unit:
        requires:
          - setup
      - e2e:
        requires:
          - setup

jobs:
  setup:
    executor: node-executor
    steps:
      *attach_workspace
      # cloning repository in the executing container and build the app
      - checkout
      - run: npm ci && npm run build
      - persist_to_workspace: # store the built files into the workspace for other jobs.
          root: *workspace_root
          paths:
            - dist
  unit:
    executor: node-executor
    steps:
      *attach_workspace
      - run: npm run test:unit
  e2e:
    executor: node-executor
    steps:
      *attach_workspace
      - run: npm run test:e2e