name: vue-components-bank CI

on: push

jobs:
  setup:
    runs:
      using: 'docker'
      image: node:lts-slim
    name: Setting up project dependencies
    steps:
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm build
