name: vue-components-bank CI

on: push

jobs:
  setup:
    runs-on: ubuntu-18.04
    name: Setting up project dependencies
    container:
      image: node:lts-slim
    steps:
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm build
